### ISSUE TITLE
Request for Enhanced Cursor Color for Improved Visibility

### ISSUE THREAD

**Issue by EduBarros101** [guobing1993/Material-Color#2]
Hello,

I am a regular user of your extension for the VSCode editor, and I would like to start by expressing my appreciation for the excellent work you've done.

However, I wanted to address a concern regarding the cursor color. Currently, the cursor is a very light shade of blue (I use the Dark Modern version), which I find to be quite weak and easily confused with other elements on the screen. As a result, it can be challenging to locate the cursor during coding sessions, leading to some inconvenience.

Therefore, I would like to kindly request that you consider testing a more vibrant cursor color option, such as yellow. I believe a stronger and more distinct color would significantly enhance the visibility of the cursor, making it easier to locate while navigating through code.

Thank you for your time and attention to this matter. I look forward to your response and any updates you might consider making to address this concern.

Best regards.

**Comment by codeime** [comment]
Thank you for your feedback.

you can customize  the cursor color in settings.json like this:

```json
 "workbench.colorCustomizations": {
        "editorCursor.foreground": ""
   },
```

**Comment by codeime** [comment]
@EduBarros101 

Thank you for your feedback.

you can customize  the cursor color in settings.json like this:

```json
 "workbench.colorCustomizations": {
        "editorCursor.foreground": ""
   },
```
